spring:
  cloud:
    config:
      name: data-transform
    stream:
      bindings:
        output:
          destination: xformed
        input:
          destination: test

#Rabbitmq configuration
  rabbitmq:
    #host: 192.168.99.100
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      #defaultZone: http://192.168.99.100:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
