server:
  port: 8081
spring:
  cloud:
    config:
      name: data-log
    stream:
      bindings:
        input:
          destination: xformed

#Rabbitmq configuration
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest



eureka:
  instance:
    hostname: data-log
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
