server:
  port: 8761
spring:
  cloud:
    config:
      name: eureka-service

eureka:
  instance:
    hostname: eureka-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl :
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
