server:
  port: 8761
spring:
  cloud:
    config:
      name: eureka-service

eureka:
  instance:
    hostname: 192.168.99.100
   # hostname: 192.168.99.101
  #  hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false