spring:
  cloud:
    config:
      name: instrument-service
    stream:
      bindings:
        output:
          destination: instruments
          #contentType: text/plain
          contentType: application/json