server:
  port: 25000
  use-forward-headers: true
  tomcat:
    internal-proxies: 
  session:
    cookie:
      http-only: false
spring:
  cloud:
    config:
      name: instrument-service
    stream:
      bindings:
        output:
          destination: instruments-saved
          #contentType: text/plain
          contentType: application/json
        input:
          destination: instruments-to-save
         # contentType: text/plain
          contentType: application/json
