server:
  port: 25004
spring:
  cloud:
    config:
      name: price-service
    stream:
      bindings:
        output:
          destination: prices
          #contentType: text/plain
          contentType: application/json