server:
  port: 80
spring:
  cloud:
    config:
      name: zuul-service
zuul:
  routes:
    web-service:
      path: /web/**
      url: http://192.168.99.100:30000/
    oanda-service:
      path: /oanda/**
      url: http://192.168.99.100:35000/
    instrument-service:
      path: /instruments/**
      url: http://192.168.99.100:25000/
    candle-service:
      path: /candles/**
      url: http://192.168.99.100:25001/
    order-service:
      path: /orders/**
      url: http://192.168.99.100:25002/
    account-service:
      path: /accounts/**
      url: http://192.168.99.100:25003/
    price-service:
      path: /prices/**
      url: http://192.168.99.100:25004/
    position-service:
      path: /positions/**
      url: http://192.168.99.100:25005/
    kibana:
      path: /kibana/**
      url: http://192.168.99.100:5601/
    rabbit:
      path: /rabbit/**
      url: http://192.168.99.100:15672/#/
    elasticsearch:
      path: /elasticsearch/**
      url: http://192.168.99.100:9200/
    zipkin:
      path: /zipkin/**
      url: http://192.168.99.100:9411/zipkin/
    config:
      path: /config/**
      url: http://192.168.99.100:8888/zuul-service/default
    eureka:
      path: /eureka/**
      url: http://192.168.99.100:8761/
