server:
  port: 80
spring:
  cloud:
    config:
      name: zuul-service
zuul:
 routes:
   zuul-service: /self/**
   price-service: /prices/**
   instrument-service: /instruments/**
   candle-service: /candles/**