version: '3'
services:

  config-service:
    build: config-service
    image: romeomaryns/config-service
  #  restart: always
    ports:
      - "8888:8888"
    logging:
      options:
        max-size: "10m"
        max-file: "10"


  db:
    image: postgres
    env_file: .env-postgres
    restart: always
    volumes:
          - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
     options:
       max-size: "10m"
       max-file: "10"

  eureka-service:
    build: eureka-service
    image: romeomaryns/eureka-service
  #  restart: always
    ports:
         - "8761:8761"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - config-service
      - rabbitmq

  helloworld:
    build: helloworld
    image: romeomaryns/hello-world
    ports:
      - "8090:8080"
    depends_on:
                - db
                - rabbitmq

  data-import:
     build: data-import
     image: romeomaryns/data-import
     depends_on:
               - config-service
               - rabbitmq

  data-log:
       build: data-log
       image: romeomaryns/data-log
       depends_on:
                 - data-transform

  data-transform:
        build: data-transform
        image: romeomaryns/data-transform
        depends_on:
                  - data-import