version: '3'
services:
  elasticsearch:
    image: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana
    #env_file: .env-kibana
    restart: always
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  db:
    image: postgres
    env_file: .env-postgres
    restart: always
    volumes:
          - /data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
     options:
       max-size: "10m"
       max-file: "10"

  config-service:
    build: basic-services/config-service
    image: romeomaryns/config-service
    restart: always
    ports:
      - "8888:8888"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  eureka-service:
    build: basic-services/eureka-service
    image: romeomaryns/eureka-service
    restart: always
    ports:
         - "8761:8761"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  zuul-service:
    build: basic-services/zuul-service
    image: romeomaryns/zuul-service
    restart: always
    ports:
         - "80:80"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  zipkin-service:
      build: basic-services/zipkin-service
      image: romeomaryns/zipkin-service
      restart: always
      ports:
        - "9411:9411"

  stream-price-service:
     build: backend-services/stream-price-service
     image: romeomaryns/stream-price-service
     depends_on:
               - config-service
               - rabbitmq
               - eureka-service
  log-service:
    build: backend-services/log-service
    image: romeomaryns/log-service
    depends_on:
              - config-service
              - rabbitmq
              - eureka-service
  price-service:
    build: backend-services/price-service
    image: romeomaryns/price-service
    depends_on:
              - config-service
              - rabbitmq
              - eureka-service
  instrument-service:
    build: backend-services/instrument-service
    image: romeomaryns/instrument-service
    depends_on:
              - config-service
              - rabbitmq
              - eureka-service
  candle-service:
    build: backend-services/candle-service
    image: romeomaryns/candle-service
    depends_on:
              - config-service
              - rabbitmq
              - eureka-service