version: '3'
services:
  helloworld:
    build: helloworld
    image: romeomaryns/hello-world
    ports:
      - "8090:8080"
    depends_on:
                - db
                - rabbitmq
  db:
    image: postgres
    env_file: .env-postgres
    volumes:
          - /data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"


  dataimport:
     build: dataimport
     image: romeomaryns/data-import
     depends_on:
               - db
               - rabbitmq

  datalog:
       build: datalog
       image: romeomaryns/data-log
       depends_on:
                 - datatransform

  datatransform:
        build: datatransform
        image: romeomaryns/data-transform
        depends_on:
                  - dataimport