server:
  port: 8081
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: xformed
        input:
          destination: test

#Rabbitmq configuration
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
